// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using RoadGuardSystem.Repositories;

#nullable disable

namespace RoadGuardSystem.cRepositories.Migrations
{
    [DbContext(typeof(RoadGuardDbContext))]
    [Migration("20260921132735_AddP230ConfirmedDatasetImmutability")]
    partial class AddP230ConfirmedDatasetImmutability
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Auditing.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AfterSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeforeSnapshot")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("ActorUserId");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_AuditLogs_CorrelationId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_AuditLogs_OccurredAtUtc");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.ToTable("AuditLogs", null, t =>
                        {
                            t.HasTrigger("TR_AuditLogs_AppendOnly");

                            t.HasCheckConstraint("CK_AuditLogs_AfterSnapshot_Json", "[AfterSnapshot] IS NULL OR ISJSON([AfterSnapshot]) = 1");

                            t.HasCheckConstraint("CK_AuditLogs_BeforeSnapshot_Json", "[BeforeSnapshot] IS NULL OR ISJSON([BeforeSnapshot]) = 1");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Catalogs.CauseCategory", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Code");

                    b.ToTable("CauseCategories", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Catalogs.DefectType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Code");

                    b.ToTable("DefectTypes", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Catalogs.SeverityRuleVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("EffectiveTo")
                        .HasColumnType("date");

                    b.Property<string>("RoadTypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("RuleDefinition")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StandardCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StandardCode", "RoadTypeCode", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_SeverityRuleVersions_ScopeVersion");

                    b.ToTable("SeverityRuleVersions", null, t =>
                        {
                            t.HasCheckConstraint("CK_SeverityRuleVersions_EffectiveDateRange", "[EffectiveTo] IS NULL OR [EffectiveTo] >= [EffectiveFrom]");

                            t.HasCheckConstraint("CK_SeverityRuleVersions_RuleDefinition_JsonObject", "ISJSON([RuleDefinition]) = 1 AND LEFT(LTRIM([RuleDefinition]), 1) = '{'");

                            t.HasCheckConstraint("CK_SeverityRuleVersions_VersionNo_Positive", "[VersionNo] > 0");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Defects.Defect", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CauseCategoryCode")
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("DefectTypeCode")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.HasKey("Id");

                    b.HasIndex("CauseCategoryCode");

                    b.HasIndex("DefectTypeCode");

                    b.ToTable("Defects", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Devices.DroneDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChecklistVersion")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Model")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("SerialNo")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("SerialNo")
                        .IsUnique()
                        .HasDatabaseName("UX_DroneDevices_SerialNo");

                    b.ToTable("DroneDevices", null, t =>
                        {
                            t.HasCheckConstraint("CK_DroneDevices_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Files.StoredFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<string>("MimeType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .IsUnicode(false)
                        .HasColumnType("varchar(120)");

                    b.Property<string>("OriginalName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<DateOnly?>("RetentionUntil")
                        .HasColumnType("date");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("int");

                    b.Property<string>("StorageUri")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StorageUri")
                        .IsUnique()
                        .HasDatabaseName("UX_Files_StorageUri");

                    b.HasIndex("UploadedByUserId");

                    b.ToTable("Files", null, t =>
                        {
                            t.HasTrigger("TR_Files_Immutable");

                            t.HasCheckConstraint("CK_Files_Checksum_Sha256Lowercase", "LEN([Checksum]) = 64 AND [Checksum] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_Files_SizeBytes_NonNegative", "[SizeBytes] >= 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Idempotency.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("OperationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OutcomeJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestFingerprint")
                        .IsRequired()
                        .HasMaxLength(64)
                        .IsUnicode(false)
                        .HasColumnType("char(64)")
                        .IsFixedLength();

                    b.HasKey("Id");

                    b.HasIndex("OperationId")
                        .HasDatabaseName("IX_IdempotencyRecords_OperationId");

                    b.HasIndex("ActorUserId", "ProjectId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("UX_IdempotencyRecords_ScopeKey");

                    b.ToTable("IdempotencyRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_IdempotencyRecords_OutcomeJson_Json", "ISJSON([OutcomeJson]) = 1");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.AccountStatusChangeLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ChangedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FromStatus")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("HandoverReference")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("ToStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_AccountStatusChangeLogs_OccurredAt");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_AccountStatusChangeLogs_TargetUserId");

                    b.ToTable("AccountStatusChangeLogs", null, t =>
                        {
                            t.HasTrigger("TR_AccountStatusChangeLogs_AppendOnly");

                            t.HasCheckConstraint("CK_AccountStatusChangeLogs_FromStatus", "[FromStatus] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_AccountStatusChangeLogs_FromToStatus_Diff", "[FromStatus] <> [ToStatus]");

                            t.HasCheckConstraint("CK_AccountStatusChangeLogs_Reason_SafeCode", "[Reason] IN ('ADMINISTRATOR_INITIATED', 'SELF_SERVICE_ACCOUNT_RECOVERY', 'REGISTRATION_APPROVED', 'SAFETY_POLICY_VIOLATION', 'NO_STATUS_CHANGE', 'ADMINISTRATIVE_LOCK', 'SECURITY_INCIDENT', 'ACCOUNT_REACTIVATED')");

                            t.HasCheckConstraint("CK_AccountStatusChangeLogs_Source_SafeCode", "[Source] IN ('ADMIN_API', 'SELF_SERVICE', 'IDENTITY_SERVICE', 'COMPLIANCE_REVIEW', 'SYSTEM')");

                            t.HasCheckConstraint("CK_AccountStatusChangeLogs_ToStatus", "[ToStatus] IN (1, 2, 3)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.ApplicationRole", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)")
                        .HasColumnName("Code");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Code");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("bit");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(254)
                        .HasColumnType("nvarchar(254)");

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("SecurityStamp")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset?>("SuspendedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email")
                        .HasFilter("[Email] IS NOT NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_NormalizedUserName");

                    b.HasIndex("RoleCode");

                    b.HasIndex("UserName")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_UserName");

                    b.ToTable("Users", null, t =>
                        {
                            t.HasCheckConstraint("CK_Users_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.PasswordResetLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("PerformedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Result")
                        .HasColumnType("tinyint");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("TargetUserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("IX_PasswordResetLogs_OccurredAt");

                    b.HasIndex("PerformedByUserId");

                    b.HasIndex("TargetUserId")
                        .HasDatabaseName("IX_PasswordResetLogs_TargetUserId");

                    b.ToTable("PasswordResetLogs", null, t =>
                        {
                            t.HasTrigger("TR_PasswordResetLogs_AppendOnly");

                            t.HasCheckConstraint("CK_PasswordResetLogs_Reason_SafeCode", "[Reason] IS NULL OR [Reason] IN ('ADMINISTRATOR_INITIATED', 'SELF_SERVICE_ACCOUNT_RECOVERY', 'REGISTRATION_APPROVED', 'SAFETY_POLICY_VIOLATION', 'NO_STATUS_CHANGE', 'ADMINISTRATIVE_LOCK', 'SECURITY_INCIDENT', 'ACCOUNT_REACTIVATED')");

                            t.HasCheckConstraint("CK_PasswordResetLogs_Result", "[Result] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_PasswordResetLogs_Source_SafeCode", "[Source] IN ('ADMIN_API', 'SELF_SERVICE', 'IDENTITY_SERVICE', 'COMPLIANCE_REVIEW', 'SYSTEM')");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .IsUnicode(false)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("SessionId")
                        .HasDatabaseName("IX_RefreshTokens_SessionId");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("UX_RefreshTokens_TokenHash");

                    b.ToTable("RefreshTokens", null, t =>
                        {
                            t.HasCheckConstraint("CK_RefreshTokens_TokenHash_NotEmpty", "LEN(LTRIM(RTRIM([TokenHash]))) >= 32");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.UserSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceMetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("IssuedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Sessions_UserId");

                    b.ToTable("Sessions", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sessions_DeviceMetadataJson_Json", "[DeviceMetadataJson] IS NULL OR ISJSON([DeviceMetadataJson]) = 1");

                            t.HasCheckConstraint("CK_Sessions_ExpiresAt", "[ExpiresAt] > [IssuedAt]");

                            t.HasCheckConstraint("CK_Sessions_RevokedAt", "[RevokedAt] IS NULL OR [RevokedAt] >= [IssuedAt]");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Messaging.ConsumerEffectReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConsumerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("EffectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("ProcessedAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId", "ConsumerName")
                        .IsUnique()
                        .HasDatabaseName("UX_ConsumerEffectReceipts_MessageConsumer");

                    b.ToTable("ConsumerEffectReceipts", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Messaging.Notification", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<DateTimeOffset?>("ReadAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("RecipientUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SourceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RecipientUserId", "ReadAt")
                        .HasDatabaseName("IX_Notifications_RecipientUserId_ReadAt");

                    b.HasIndex("RecipientUserId", "SourceEntityType", "SourceEntityId", "EventType")
                        .IsUnique()
                        .HasDatabaseName("UX_Notifications_RecipientSourceEvent");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Messaging.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("IX_OutboxMessages_CorrelationId");

                    b.HasIndex("OccurredAtUtc")
                        .HasDatabaseName("IX_OutboxMessages_OccurredAtUtc");

                    b.ToTable("OutboxMessages", null, t =>
                        {
                            t.HasCheckConstraint("CK_OutboxMessages_PayloadJson_Json", "ISJSON([PayloadJson]) = 1");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.HandoverDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AcceptedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DocumentNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HandoverDate")
                        .HasColumnType("date");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.HasIndex("AcceptedByUserId");

                    b.HasIndex("FileId");

                    b.HasIndex("ProjectId", "DocumentNo")
                        .IsUnique()
                        .HasDatabaseName("UX_HandoverDocuments_ProjectId_DocumentNo");

                    b.ToTable("HandoverDocuments", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date");

                    b.Property<int?>("EngineeringUtmSrid")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("ProjectCode")
                        .IsUnique()
                        .HasDatabaseName("UX_Projects_ProjectCode");

                    b.ToTable("Projects", null, t =>
                        {
                            t.HasCheckConstraint("CK_Projects_DateRange", "[EndDate] IS NULL OR [StartDate] IS NULL OR [EndDate] >= [StartDate]");

                            t.HasCheckConstraint("CK_Projects_EngineeringUtmSrid", "[EngineeringUtmSrid] IS NULL OR [EngineeringUtmSrid] IN (32648, 32649)");

                            t.HasCheckConstraint("CK_Projects_Status", "[Status] IN (1, 2, 3)");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.ProjectMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleCode")
                        .IsRequired()
                        .HasMaxLength(40)
                        .IsUnicode(false)
                        .HasColumnType("varchar(40)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId")
                        .IsUnique()
                        .HasDatabaseName("UX_ProjectMembers_ActivePrimaryProjectManager")
                        .HasFilter("[IsPrimary] = 1 AND [Status] = 1");

                    b.HasIndex("RoleCode");

                    b.HasIndex("UserId");

                    b.HasIndex("ProjectId", "UserId")
                        .HasDatabaseName("IX_ProjectMembers_ProjectId_UserId");

                    b.ToTable("ProjectMembers", null, t =>
                        {
                            t.HasCheckConstraint("CK_ProjectMembers_EffectiveDateRange", "[ValidTo] IS NULL OR [ValidTo] >= [ValidFrom]");

                            t.HasCheckConstraint("CK_ProjectMembers_PrimaryRole", "[IsPrimary] = 0 OR [RoleCode] = 'PM'");

                            t.HasCheckConstraint("CK_ProjectMembers_Status", "[Status] IN (1, 2)");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.RoadSection", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_RoadSections_ProjectId_Code");

                    b.ToTable("RoadSections", (string)null);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.RoadSectionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChangeReason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("EffectiveFrom")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<LineString>("Geometry")
                        .IsRequired()
                        .HasColumnType("geometry");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoadSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoadSectionId")
                        .IsUnique()
                        .HasDatabaseName("UX_RoadSectionVersions_Current")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("RoadSectionId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_RoadSectionVersions_RoadSectionId_VersionNo");

                    b.ToTable("RoadSectionVersions", null, t =>
                        {
                            t.HasTrigger("TR_RoadSectionVersions_Immutable");

                            t.HasCheckConstraint("CK_RoadSectionVersions_Geometry_AllowedSrid", "[Geometry].STSrid IN (32648, 32649)");

                            t.HasCheckConstraint("CK_RoadSectionVersions_Geometry_LineString", "[Geometry].STGeometryType() = 'LineString'");

                            t.HasCheckConstraint("CK_RoadSectionVersions_VersionNo_Positive", "[VersionNo] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("DroneDeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("FlightNo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .IsUnicode(false)
                        .HasColumnType("varchar(80)");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("DroneDeviceId");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("SurveyId", "FlightNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Flights_SurveyFlightNo");

                    b.ToTable("Flights", null, t =>
                        {
                            t.HasCheckConstraint("CK_Flights_TimestampOrder", "[EndedAt] IS NULL OR [EndedAt] >= [StartedAt]");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.QualityCheck", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("CheckType")
                        .HasColumnType("tinyint");

                    b.Property<DateTimeOffset>("CheckedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte>("CheckedBy")
                        .HasColumnType("tinyint");

                    b.Property<byte>("ExecutionStage")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("InitiatedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("MeasuredValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Scope")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SurveyDataVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SurveyFileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Threshold")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("InitiatedByUserId");

                    b.HasIndex("SurveyDataVersionId")
                        .HasDatabaseName("IX_QualityChecks_SurveyDataVersionId");

                    b.HasIndex("SurveyFileId")
                        .HasDatabaseName("IX_QualityChecks_SurveyFileId");

                    b.ToTable("QualityChecks", null, t =>
                        {
                            t.HasCheckConstraint("CK_QualityChecks_CheckType", "[CheckType] IN (1, 2, 3, 4, 5, 6, 7, 8, 9)");

                            t.HasCheckConstraint("CK_QualityChecks_CheckedBy", "[CheckedBy] IN (1, 2)");

                            t.HasCheckConstraint("CK_QualityChecks_ExactlyOneTarget", "([Scope] = 1 AND [SurveyFileId] IS NOT NULL AND [SurveyDataVersionId] IS NULL) OR ([Scope] = 2 AND [SurveyFileId] IS NULL AND [SurveyDataVersionId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_QualityChecks_ExecutionStage", "[ExecutionStage] IN (1, 2)");

                            t.HasCheckConstraint("CK_QualityChecks_MeasuredValue_Json", "[MeasuredValue] IS NULL OR ISJSON([MeasuredValue]) = 1");

                            t.HasCheckConstraint("CK_QualityChecks_Scope", "[Scope] IN (1, 2)");

                            t.HasCheckConstraint("CK_QualityChecks_StageActor", "([ExecutionStage] = 1 AND [CheckedBy] = 1) OR ([ExecutionStage] = 2 AND [CheckedBy] = 2 AND [InitiatedByUserId] IS NULL)");

                            t.HasCheckConstraint("CK_QualityChecks_Status", "[Status] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_QualityChecks_Threshold_Json", "[Threshold] IS NULL OR ISJSON([Threshold]) = 1");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SupplementarySurveyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ApprovedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("ApprovedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RequestedScope")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoundNo")
                        .HasColumnType("int");

                    b.Property<string>("SourcePreservationNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SurveyRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedByUserId");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("SurveyRequestId")
                        .HasDatabaseName("IX_SupplementarySurveyRequests_SurveyRequestId");

                    b.HasIndex("SurveyId", "RoundNo")
                        .IsUnique()
                        .HasDatabaseName("UX_SupplementarySurveyRequests_SurveyRound");

                    b.ToTable("SupplementarySurveyRequests", null, t =>
                        {
                            t.HasCheckConstraint("CK_SupplementarySurveyRequests_Approval", "([ApprovedByUserId] IS NULL AND [ApprovedAt] IS NULL) OR ([ApprovedByUserId] IS NOT NULL AND [ApprovedAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SupplementarySurveyRequests_RequestedScope_JsonObject", "ISJSON([RequestedScope]) = 1 AND LEFT(LTRIM([RequestedScope]), 1) = '{'");

                            t.HasCheckConstraint("CK_SupplementarySurveyRequests_RoundNo", "[RoundNo] > 0");

                            t.HasCheckConstraint("CK_SupplementarySurveyRequests_Status", "[Status] IN (1, 2, 3, 4, 5, 6, 7)");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.Survey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("BaselineConfirmedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid?>("BaselineConfirmedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsBaselineConfirmed")
                        .HasColumnType("bit");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoadSectionVersionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SurveyRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SurveyType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("BaselineConfirmedByUserId");

                    b.HasIndex("RoadSectionVersionId")
                        .HasDatabaseName("IX_Surveys_RoadSectionVersionId");

                    b.HasIndex("SurveyRequestId");

                    b.HasIndex("ProjectId", "Status")
                        .HasDatabaseName("IX_Surveys_ProjectStatus");

                    b.ToTable("Surveys", null, t =>
                        {
                            t.HasTrigger("TR_Surveys_ScopeIntegrity");

                            t.HasCheckConstraint("CK_Surveys_BaselineConfirmation", "([IsBaselineConfirmed] = 0 AND [BaselineConfirmedByUserId] IS NULL AND [BaselineConfirmedAt] IS NULL) OR ([IsBaselineConfirmed] = 1 AND [BaselineConfirmedByUserId] IS NOT NULL AND [BaselineConfirmedAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Surveys_Status", "[Status] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_Surveys_SurveyType", "[SurveyType] IN (1, 2, 3)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("AcceptedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("AssignedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("AssignedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("EndedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("OperatorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReassignmentReason")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTimeOffset?>("RejectedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("RejectionReason")
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SurveyRequestId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AssignedByUserId");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("SurveyRequestId")
                        .IsUnique()
                        .HasDatabaseName("UX_SurveyAssignments_ActiveRequest")
                        .HasFilter("[EndedAt] IS NULL");

                    b.HasIndex("SurveyRequestId", "EndedAt")
                        .HasDatabaseName("IX_SurveyAssignments_RequestEndedAt");

                    b.ToTable("SurveyAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_SurveyAssignments_AcceptanceRejection", "[AcceptedAt] IS NULL OR [RejectedAt] IS NULL");

                            t.HasCheckConstraint("CK_SurveyAssignments_ActiveReassignmentReason", "[EndedAt] IS NOT NULL OR [ReassignmentReason] IS NULL");

                            t.HasCheckConstraint("CK_SurveyAssignments_ReassignmentNotRejected", "[ReassignmentReason] IS NULL OR [RejectedAt] IS NULL");

                            t.HasCheckConstraint("CK_SurveyAssignments_Rejection", "([RejectedAt] IS NULL AND [RejectionReason] IS NULL) OR ([RejectedAt] IS NOT NULL AND LEN(LTRIM(RTRIM([RejectionReason]))) > 0 AND [EndedAt] IS NOT NULL)");

                            t.HasCheckConstraint("CK_SurveyAssignments_TimestampOrder", "([AcceptedAt] IS NULL OR [AcceptedAt] >= [AssignedAt]) AND ([RejectedAt] IS NULL OR [RejectedAt] >= [AssignedAt]) AND ([EndedAt] IS NULL OR [EndedAt] >= [AssignedAt])");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyDataVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ConfirmedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<byte?>("ConfirmedBy")
                        .HasColumnType("tinyint");

                    b.Property<byte>("IntegrityStatus")
                        .HasColumnType("tinyint");

                    b.Property<string>("SourceManifest")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("VersionNo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyId", "VersionNo")
                        .IsUnique()
                        .HasDatabaseName("UX_SurveyDataVersions_SurveyVersion");

                    b.ToTable("SurveyDataVersions", null, t =>
                        {
                            t.HasTrigger("TR_SurveyDataVersions_Immutable");

                            t.HasCheckConstraint("CK_SurveyDataVersions_IntegrityStatus", "[IntegrityStatus] IN (1, 2, 3)");

                            t.HasCheckConstraint("CK_SurveyDataVersions_ServerConfirmation", "([Status] = 3 AND [IntegrityStatus] = 2 AND [ConfirmedAt] IS NOT NULL AND [ConfirmedBy] = 1) OR ([Status] <> 3 AND [ConfirmedAt] IS NULL AND [ConfirmedBy] IS NULL)");

                            t.HasCheckConstraint("CK_SurveyDataVersions_SourceManifest_JsonArray", "ISJSON([SourceManifest]) = 1 AND LEFT(LTRIM([SourceManifest]), 1) = '['");

                            t.HasCheckConstraint("CK_SurveyDataVersions_Status", "[Status] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_SurveyDataVersions_VersionNo", "[VersionNo] > 0");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyFile", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CaptureEndedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset?>("CaptureStartedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasColumnType("char(64)");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("FileType")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("FlightId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SurveyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SyncStatus")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .HasDatabaseName("IX_SurveyFiles_FileId");

                    b.HasIndex("FlightId")
                        .HasDatabaseName("IX_SurveyFiles_FlightId");

                    b.HasIndex("SurveyId")
                        .HasDatabaseName("IX_SurveyFiles_SurveyId");

                    b.ToTable("SurveyFiles", null, t =>
                        {
                            t.HasTrigger("TR_SurveyFiles_ScopeIntegrity");

                            t.HasCheckConstraint("CK_SurveyFiles_Checksum_Sha256Lowercase", "LEN([Checksum]) = 64 AND [Checksum] COLLATE Latin1_General_100_BIN2 NOT LIKE '%[^0-9a-f]%'");

                            t.HasCheckConstraint("CK_SurveyFiles_FileType", "[FileType] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_SurveyFiles_SyncStatus", "[SyncStatus] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_SurveyFiles_TimestampOrder", "[CaptureEndedAt] IS NULL OR [CaptureStartedAt] IS NULL OR [CaptureEndedAt] >= [CaptureStartedAt]");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("PlannedEndAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("PlannedStartAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoadSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<byte>("SurveyType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("RoadSectionId");

                    b.HasIndex("ProjectId", "RoadSectionId", "PlannedStartAt")
                        .HasDatabaseName("IX_SurveyPlans_ProjectRoadStart");

                    b.HasIndex("ProjectId", "RoadSectionId", "SurveyType")
                        .IsUnique()
                        .HasDatabaseName("UX_SurveyPlans_ActiveScope")
                        .HasFilter("[Status] IN (1, 2, 3)");

                    b.ToTable("SurveyPlans", null, t =>
                        {
                            t.HasTrigger("TR_SurveyPlans_ScopeIntegrity");

                            t.HasCheckConstraint("CK_SurveyPlans_PlannedDateRange", "[PlannedEndAt] >= [PlannedStartAt]");

                            t.HasCheckConstraint("CK_SurveyPlans_Status", "[Status] IN (1, 2, 3, 4, 5)");

                            t.HasCheckConstraint("CK_SurveyPlans_SurveyType", "[SurveyType] IN (1, 2, 3)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyPlanPostponement", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("NewPlannedStartAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<DateTimeOffset>("PostponedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SurveyPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("SurveyPlanId", "PostponedAt")
                        .HasDatabaseName("IX_SurveyPlanPostponements_PlanId_PostponedAt");

                    b.ToTable("SurveyPlanPostponements", null, t =>
                        {
                            t.HasTrigger("TR_SurveyPlanPostponements_AppendOnly");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CancellationReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("CancelledAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("RequestedAt")
                        .HasColumnType("datetimeoffset(7)");

                    b.Property<Guid>("RequestedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoadSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SurveyPlanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("SurveyType")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("RequestedByUserId");

                    b.HasIndex("RoadSectionId");

                    b.HasIndex("SurveyPlanId")
                        .IsUnique()
                        .HasDatabaseName("UX_SurveyRequests_ActivePlan")
                        .HasFilter("[SurveyPlanId] IS NOT NULL AND [Status] IN (1, 2, 4, 5, 6, 7, 10)");

                    b.HasIndex("ProjectId", "RoadSectionId", "Status")
                        .HasDatabaseName("IX_SurveyRequests_ProjectRoadStatus");

                    b.ToTable("SurveyRequests", null, t =>
                        {
                            t.HasTrigger("TR_SurveyRequests_ScopeIntegrity");

                            t.HasCheckConstraint("CK_SurveyRequests_Cancellation", "([Status] = 9 AND [CancelledAt] IS NOT NULL AND LEN(LTRIM(RTRIM([CancellationReason]))) > 0) OR ([Status] <> 9 AND [CancelledAt] IS NULL AND [CancellationReason] IS NULL)");

                            t.HasCheckConstraint("CK_SurveyRequests_Status", "[Status] IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10)");

                            t.HasCheckConstraint("CK_SurveyRequests_SurveyType", "[SurveyType] IN (1, 2, 3)");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Warranties.Warranty", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateOnly>("HandoverDate")
                        .HasColumnType("date");

                    b.Property<Guid?>("HandoverDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("RetainedValue")
                        .HasPrecision(19, 2)
                        .HasColumnType("decimal(19,2)");

                    b.Property<Guid?>("RoadSectionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Scope")
                        .HasColumnType("tinyint");

                    b.Property<Guid?>("SourceDocumentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte>("Status")
                        .HasColumnType("tinyint");

                    b.Property<string>("Terms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("WarrantyEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("WarrantyStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("HandoverDocumentId");

                    b.HasIndex("ProjectId")
                        .HasDatabaseName("IX_Warranties_ProjectId");

                    b.HasIndex("RoadSectionId")
                        .HasDatabaseName("IX_Warranties_RoadSectionId");

                    b.HasIndex("SourceDocumentId");

                    b.ToTable("Warranties", null, t =>
                        {
                            t.HasCheckConstraint("CK_Warranties_DateRange", "[WarrantyEndDate] >= [WarrantyStartDate]");

                            t.HasCheckConstraint("CK_Warranties_RetainedValue_NonNegative", "[RetainedValue] IS NULL OR [RetainedValue] >= 0");

                            t.HasCheckConstraint("CK_Warranties_Scope", "[Scope] IN (1, 2, 3, 4)");

                            t.HasCheckConstraint("CK_Warranties_ScopeRoadSection", "([Scope] <> 1 OR [RoadSectionId] IS NULL) AND ([Scope] <> 2 OR [RoadSectionId] IS NOT NULL)");

                            t.HasCheckConstraint("CK_Warranties_Status", "[Status] IN (1, 2, 3, 4)");
                        });
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Auditing.AuditLog", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ActorUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Defects.Defect", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Catalogs.CauseCategory", null)
                        .WithMany()
                        .HasForeignKey("CauseCategoryCode")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Catalogs.DefectType", null)
                        .WithMany()
                        .HasForeignKey("DefectTypeCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Files.StoredFile", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UploadedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.AccountStatusChangeLog", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", "ChangedByUser")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", "TargetUser")
                        .WithMany("TargetAccountStatusChangeLogs")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChangedByUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.PasswordResetLog", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", "PerformedByUser")
                        .WithMany()
                        .HasForeignKey("PerformedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", "TargetUser")
                        .WithMany("TargetPasswordResetLogs")
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PerformedByUser");

                    b.Navigation("TargetUser");
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.RefreshToken", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.UserSession", "Session")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Session");
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.UserSession", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", "User")
                        .WithMany("Sessions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Messaging.ConsumerEffectReceipt", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Messaging.OutboxMessage", null)
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Messaging.Notification", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RecipientUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.HandoverDocument", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AcceptedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.ProjectMember", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleCode")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.RoadSection", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Projects.RoadSectionVersion", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.RoadSection", null)
                        .WithMany()
                        .HasForeignKey("RoadSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.Flight", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Devices.DroneDevice", null)
                        .WithMany()
                        .HasForeignKey("DroneDeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.QualityCheck", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("InitiatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.SurveyDataVersion", null)
                        .WithMany()
                        .HasForeignKey("SurveyDataVersionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.SurveyFile", null)
                        .WithMany()
                        .HasForeignKey("SurveyFileId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SupplementarySurveyRequest", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("ApprovedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.SurveyRequest", null)
                        .WithMany()
                        .HasForeignKey("SurveyRequestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.Survey", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("BaselineConfirmedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.RoadSectionVersion", null)
                        .WithMany()
                        .HasForeignKey("RoadSectionVersionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.SurveyRequest", null)
                        .WithMany()
                        .HasForeignKey("SurveyRequestId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyAssignment", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("AssignedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.SurveyRequest", null)
                        .WithMany()
                        .HasForeignKey("SurveyRequestId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyDataVersion", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyFile", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("FileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.Flight", null)
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.Survey", null)
                        .WithMany()
                        .HasForeignKey("SurveyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyPlan", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.RoadSection", null)
                        .WithMany()
                        .HasForeignKey("RoadSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyPlanPostponement", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.SurveyPlan", null)
                        .WithMany()
                        .HasForeignKey("SurveyPlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Surveys.SurveyRequest", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("RequestedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.RoadSection", null)
                        .WithMany()
                        .HasForeignKey("RoadSectionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Surveys.SurveyPlan", null)
                        .WithMany()
                        .HasForeignKey("SurveyPlanId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Warranties.Warranty", b =>
                {
                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.HandoverDocument", null)
                        .WithMany()
                        .HasForeignKey("HandoverDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.Project", null)
                        .WithMany()
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RoadGuardSystem.BusinessObjects.Projects.RoadSection", null)
                        .WithMany()
                        .HasForeignKey("RoadSectionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("RoadGuardSystem.BusinessObjects.Files.StoredFile", null)
                        .WithMany()
                        .HasForeignKey("SourceDocumentId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.ApplicationUser", b =>
                {
                    b.Navigation("Sessions");

                    b.Navigation("TargetAccountStatusChangeLogs");

                    b.Navigation("TargetPasswordResetLogs");
                });

            modelBuilder.Entity("RoadGuardSystem.BusinessObjects.Identity.UserSession", b =>
                {
                    b.Navigation("RefreshTokens");
                });
#pragma warning restore 612, 618
        }
    }
}
