namespace RoadGuardSystem.DTOs;

// Explicit property mappings preserve wire shape while repositories exchange independent facts.
public static class BoundaryFactMappings
{
    public static object? ToFacts(object? value) => value switch
    {
        global::RoadGuardSystem.DTOs.Processing.AiMockRunView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockRunViewFact)item,
        global::RoadGuardSystem.DTOs.Processing.AiMockRunView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockRunViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Processing.AiMockScopeRequest item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockScopeRequestFact)item,
        global::RoadGuardSystem.DTOs.Processing.AiMockScopeRequest[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockScopeRequestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.AsBuiltLayoutInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltLayoutInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.AsBuiltLayoutInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltLayoutInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.AsBuiltSlabInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltSlabInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.AsBuiltSlabInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltSlabInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Defects.CandidateDecisionResponseDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.CandidateDecisionResponseFact)item,
        global::RoadGuardSystem.DTOs.Defects.CandidateDecisionResponseDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.CandidateDecisionResponseFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Cases.CaseConclusionViewDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CaseConclusionViewFact)item,
        global::RoadGuardSystem.DTOs.Cases.CaseConclusionViewDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CaseConclusionViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.CaseDefectSnapshotV1 item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseDefectSnapshotV1Fact)item,
        global::RoadGuardSystem.DTOs.Reporting.CaseDefectSnapshotV1[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseDefectSnapshotV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.CaseEvidenceRefV1 item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseEvidenceRefV1Fact)item,
        global::RoadGuardSystem.DTOs.Reporting.CaseEvidenceRefV1[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseEvidenceRefV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Cases.CasePageDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePageFact)item,
        global::RoadGuardSystem.DTOs.Cases.CasePageDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePageFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.CasePublicationRefV1 item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CasePublicationRefV1Fact)item,
        global::RoadGuardSystem.DTOs.Reporting.CasePublicationRefV1[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CasePublicationRefV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Cases.CasePublicationResponseDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePublicationResponseFact)item,
        global::RoadGuardSystem.DTOs.Cases.CasePublicationResponseDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePublicationResponseFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.CaseReadFactV1 item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReadFactV1Fact)item,
        global::RoadGuardSystem.DTOs.Reporting.CaseReadFactV1[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReadFactV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.CaseReportRefV1 item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReportRefV1Fact)item,
        global::RoadGuardSystem.DTOs.Reporting.CaseReportRefV1[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReportRefV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.ChainageCalibrationInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageCalibrationInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.ChainageCalibrationInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageCalibrationInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.ChainageControl item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageControlFact)item,
        global::RoadGuardSystem.DTOs.Projects.ChainageControl[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageControlFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.ConfirmRetentionBasisRequest item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ConfirmRetentionBasisRequestFact)item,
        global::RoadGuardSystem.DTOs.Retention.ConfirmRetentionBasisRequest[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ConfirmRetentionBasisRequestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Processing.CreateAiMockRunRequest item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.CreateAiMockRunRequestFact)item,
        global::RoadGuardSystem.DTOs.Processing.CreateAiMockRunRequest[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.CreateAiMockRunRequestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Exports.CreateExportRequestDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.CreateExportRequestFact)item,
        global::RoadGuardSystem.DTOs.Exports.CreateExportRequestDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.CreateExportRequestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.CreateRetentionEvaluationRequest item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionEvaluationRequestFact)item,
        global::RoadGuardSystem.DTOs.Retention.CreateRetentionEvaluationRequest[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionEvaluationRequestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.CreateRetentionHoldRequest item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionHoldRequestFact)item,
        global::RoadGuardSystem.DTOs.Retention.CreateRetentionHoldRequest[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionHoldRequestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.CrsControlPoint item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsControlPointFact)item,
        global::RoadGuardSystem.DTOs.Projects.CrsControlPoint[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsControlPointFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.CrsEllipsoidDefinition item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsEllipsoidDefinitionFact)item,
        global::RoadGuardSystem.DTOs.Projects.CrsEllipsoidDefinition[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsEllipsoidDefinitionFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.CrsProfileInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.CrsProfileInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.CrsProfileView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileViewFact)item,
        global::RoadGuardSystem.DTOs.Projects.CrsProfileView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.CrsProjectionDefinition item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProjectionDefinitionFact)item,
        global::RoadGuardSystem.DTOs.Projects.CrsProjectionDefinition[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProjectionDefinitionFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.CrsTransformOperation item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsTransformOperationFact)item,
        global::RoadGuardSystem.DTOs.Projects.CrsTransformOperation[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsTransformOperationFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Defects.DefectGeometryDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectGeometryFact)item,
        global::RoadGuardSystem.DTOs.Defects.DefectGeometryDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectGeometryFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Defects.DefectPageDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectPageFact)item,
        global::RoadGuardSystem.DTOs.Defects.DefectPageDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectPageFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.DefectReadFactV1 item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.DefectReadFactV1Fact)item,
        global::RoadGuardSystem.DTOs.Reporting.DefectReadFactV1[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.DefectReadFactV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Defects.DefectViewDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectViewFact)item,
        global::RoadGuardSystem.DTOs.Defects.DefectViewDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Exports.ExportFileDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportFileFact)item,
        global::RoadGuardSystem.DTOs.Exports.ExportFileDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportFileFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Exports.ExportLabelDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportLabelFact)item,
        global::RoadGuardSystem.DTOs.Exports.ExportLabelDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportLabelFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Exports.ExportManifestV1Dto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportManifestV1Fact)item,
        global::RoadGuardSystem.DTOs.Exports.ExportManifestV1Dto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportManifestV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Exports.ExportSectionDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSectionFact)item,
        global::RoadGuardSystem.DTOs.Exports.ExportSectionDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSectionFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Exports.ExportSnapshotPayloadDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSnapshotPayloadFact)item,
        global::RoadGuardSystem.DTOs.Exports.ExportSnapshotPayloadDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSnapshotPayloadFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Exports.ExportSourceRevisionDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSourceRevisionFact)item,
        global::RoadGuardSystem.DTOs.Exports.ExportSourceRevisionDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSourceRevisionFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceDeclaration item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceDeclarationFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceDeclaration[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceDeclarationFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceReuseInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceReuseInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceReuseInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceReuseInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldHandoverInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldHandoverInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldHandoverInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldHandoverInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldLocationImpactActionInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldLocationImpactActionInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldLocationImpactActionInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldLocationImpactActionInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldMeasurementInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldMeasurementInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldMeasurementInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldMeasurementInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldPositionProofInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldPositionProofInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldPositionProofInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldPositionProofInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldReviewInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldReviewInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldReviewView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewViewFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldReviewView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldStartInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldStartInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldStartInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldStartInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionViewFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldTaskActionInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskActionInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldTaskActionInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskActionInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldTaskCreateInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskCreateInputFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldTaskCreateInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskCreateInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldTaskView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskViewFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldTaskView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceFacts item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceFactsFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceFacts[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceFactsFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceQuery item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceQueryFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceQuery[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceQueryFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Inspections.FieldWorkflowResult item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldWorkflowResultFact)item,
        global::RoadGuardSystem.DTOs.Inspections.FieldWorkflowResult[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldWorkflowResultFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryAffectedReference item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryAffectedReferenceFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryAffectedReference[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryAffectedReferenceFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryConfirmInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryConfirmInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryConfirmInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryConfirmInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryDraftInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryDraftInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryDraftReadiness item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftReadinessFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryDraftReadiness[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftReadinessFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryDraftView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftViewFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryDraftView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryImpactDecisionInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactDecisionInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryImpactDecisionInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactDecisionInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryImpactInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryImpactInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryMapFeature item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapFeatureFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryMapFeature[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapFeatureFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryMapLayer item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapLayerFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryMapLayer[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapLayerFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryMapManifest item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapManifestFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryMapManifest[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapManifestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryMapPage item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPageFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryMapPage[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPageFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryMapPublishInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPublishInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryMapPublishInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPublishInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryMapSnapshot item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapSnapshotFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryMapSnapshot[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapSnapshotFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryPackageView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPackageViewFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryPackageView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPackageViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryPoint item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPointFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryPoint[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPointFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryPreview item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPreviewFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryPreview[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPreviewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.GeometryShape item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryShapeFact)item,
        global::RoadGuardSystem.DTOs.Projects.GeometryShape[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryShapeFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Cases.InternalCaseDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.InternalCaseFact)item,
        global::RoadGuardSystem.DTOs.Cases.InternalCaseDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.InternalCaseFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Labels.LabelAnnotationDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.LabelAnnotationFact)item,
        global::RoadGuardSystem.DTOs.Labels.LabelAnnotationDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.LabelAnnotationFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.NativeAlignmentInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.NativeAlignmentInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.NativeAlignmentPrimitive item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentPrimitiveFact)item,
        global::RoadGuardSystem.DTOs.Projects.NativeAlignmentPrimitive[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentPrimitiveFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reports.OwnReportDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportFact)item,
        global::RoadGuardSystem.DTOs.Reports.OwnReportDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reports.OwnReportEvidenceDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportEvidenceFact)item,
        global::RoadGuardSystem.DTOs.Reports.OwnReportEvidenceDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportEvidenceFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reports.OwnReportPageDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportPageFact)item,
        global::RoadGuardSystem.DTOs.Reports.OwnReportPageDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportPageFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reports.OwnReportSupplementDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportSupplementFact)item,
        global::RoadGuardSystem.DTOs.Reports.OwnReportSupplementDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportSupplementFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reports.OwnReportUpdateDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportUpdateFact)item,
        global::RoadGuardSystem.DTOs.Reports.OwnReportUpdateDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportUpdateFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.PavementGeometryPreview item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementGeometryPreviewFact)item,
        global::RoadGuardSystem.DTOs.Projects.PavementGeometryPreview[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementGeometryPreviewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.PavementLayoutInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.PavementLayoutInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.PavementLayoutPreview item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutPreviewFact)item,
        global::RoadGuardSystem.DTOs.Projects.PavementLayoutPreview[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutPreviewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.PavementPlanCreateInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementPlanCreateInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.PavementPlanCreateInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementPlanCreateInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.PavementWidthInterval item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementWidthIntervalFact)item,
        global::RoadGuardSystem.DTOs.Projects.PavementWidthInterval[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementWidthIntervalFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.PlannedSlabCell item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PlannedSlabCellFact)item,
        global::RoadGuardSystem.DTOs.Projects.PlannedSlabCell[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PlannedSlabCellFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ProjectSummaryV1 item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ProjectSummaryV1Fact)item,
        global::RoadGuardSystem.DTOs.Reporting.ProjectSummaryV1[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ProjectSummaryV1Fact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.ReleaseRetentionHoldRequest item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ReleaseRetentionHoldRequestFact)item,
        global::RoadGuardSystem.DTOs.Retention.ReleaseRetentionHoldRequest[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ReleaseRetentionHoldRequestFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reports.ReportEvidenceLocationDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.ReportEvidenceLocationFact)item,
        global::RoadGuardSystem.DTOs.Reports.ReportEvidenceLocationDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.ReportEvidenceLocationFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingAvailabilityDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingAvailabilityFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingAvailabilityDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingAvailabilityFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingCaptureDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingCaptureFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingCaptureDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingCaptureFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingDimensionsDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingDimensionsFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingDimensionsDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingDimensionsFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingFileDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFileFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingFileDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFileFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingFiltersDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFiltersFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingFiltersDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFiltersFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingItemDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingItemFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingItemDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingItemFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingMetricDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingMetricFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingMetricDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingMetricFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingSourceRefDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingSourceRefFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingSourceRefDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingSourceRefFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Reporting.ReportingTimelineItemDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingTimelineItemFact)item,
        global::RoadGuardSystem.DTOs.Reporting.ReportingTimelineItemDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingTimelineItemFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.RetentionBasisView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionBasisViewFact)item,
        global::RoadGuardSystem.DTOs.Retention.RetentionBasisView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionBasisViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.RetentionEvaluationView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionEvaluationViewFact)item,
        global::RoadGuardSystem.DTOs.Retention.RetentionEvaluationView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionEvaluationViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.RetentionFileView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionFileViewFact)item,
        global::RoadGuardSystem.DTOs.Retention.RetentionFileView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionFileViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.RetentionHoldView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionHoldViewFact)item,
        global::RoadGuardSystem.DTOs.Retention.RetentionHoldView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionHoldViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.RetentionItemView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionItemViewFact)item,
        global::RoadGuardSystem.DTOs.Retention.RetentionItemView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionItemViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.RetentionReferenceView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionReferenceViewFact)item,
        global::RoadGuardSystem.DTOs.Retention.RetentionReferenceView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionReferenceViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Retention.RetentionWarrantyView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionWarrantyViewFact)item,
        global::RoadGuardSystem.DTOs.Retention.RetentionWarrantyView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionWarrantyViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.RoadGeometryVersionView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RoadGeometryVersionViewFact)item,
        global::RoadGuardSystem.DTOs.Projects.RoadGeometryVersionView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RoadGeometryVersionViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.RouteSystemInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.RouteSystemInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.RouteSystemView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemViewFact)item,
        global::RoadGuardSystem.DTOs.Projects.RouteSystemView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.SegmentDefinition item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentDefinitionFact)item,
        global::RoadGuardSystem.DTOs.Projects.SegmentDefinition[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentDefinitionFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.SegmentGeometry item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryFact)item,
        global::RoadGuardSystem.DTOs.Projects.SegmentGeometry[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.SegmentGeometryView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryViewFact)item,
        global::RoadGuardSystem.DTOs.Projects.SegmentGeometryView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.SegmentPreview item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPreviewFact)item,
        global::RoadGuardSystem.DTOs.Projects.SegmentPreview[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPreviewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.SegmentPublishInput item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPublishInputFact)item,
        global::RoadGuardSystem.DTOs.Projects.SegmentPublishInput[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPublishInputFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.SegmentSetView item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentSetViewFact)item,
        global::RoadGuardSystem.DTOs.Projects.SegmentSetView[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentSetViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.SlabGeometrySnapshot item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SlabGeometrySnapshotFact)item,
        global::RoadGuardSystem.DTOs.Projects.SlabGeometrySnapshot[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SlabGeometrySnapshotFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Labels.TrainingLabelPageDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelPageFact)item,
        global::RoadGuardSystem.DTOs.Labels.TrainingLabelPageDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelPageFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Labels.TrainingLabelViewDto item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelViewFact)item,
        global::RoadGuardSystem.DTOs.Labels.TrainingLabelViewDto[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelViewFact)item).ToArray(),
        global::RoadGuardSystem.DTOs.Projects.WidthProfileItem item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.WidthProfileItemFact)item,
        global::RoadGuardSystem.DTOs.Projects.WidthProfileItem[] items => items.Select(item => (global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.WidthProfileItemFact)item).ToArray(),
        _ => value
    };
    public static object? ToWire(object? value) => value switch
    {
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockRunViewFact item => (global::RoadGuardSystem.DTOs.Processing.AiMockRunView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockRunViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Processing.AiMockRunView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockScopeRequestFact item => (global::RoadGuardSystem.DTOs.Processing.AiMockScopeRequest)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.AiMockScopeRequestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Processing.AiMockScopeRequest)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltLayoutInputFact item => (global::RoadGuardSystem.DTOs.Projects.AsBuiltLayoutInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltLayoutInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.AsBuiltLayoutInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltSlabInputFact item => (global::RoadGuardSystem.DTOs.Projects.AsBuiltSlabInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.AsBuiltSlabInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.AsBuiltSlabInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.CandidateDecisionResponseFact item => (global::RoadGuardSystem.DTOs.Defects.CandidateDecisionResponseDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.CandidateDecisionResponseFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Defects.CandidateDecisionResponseDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CaseConclusionViewFact item => (global::RoadGuardSystem.DTOs.Cases.CaseConclusionViewDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CaseConclusionViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Cases.CaseConclusionViewDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseDefectSnapshotV1Fact item => (global::RoadGuardSystem.DTOs.Reporting.CaseDefectSnapshotV1)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseDefectSnapshotV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.CaseDefectSnapshotV1)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseEvidenceRefV1Fact item => (global::RoadGuardSystem.DTOs.Reporting.CaseEvidenceRefV1)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseEvidenceRefV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.CaseEvidenceRefV1)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePageFact item => (global::RoadGuardSystem.DTOs.Cases.CasePageDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePageFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Cases.CasePageDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CasePublicationRefV1Fact item => (global::RoadGuardSystem.DTOs.Reporting.CasePublicationRefV1)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CasePublicationRefV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.CasePublicationRefV1)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePublicationResponseFact item => (global::RoadGuardSystem.DTOs.Cases.CasePublicationResponseDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.CasePublicationResponseFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Cases.CasePublicationResponseDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReadFactV1Fact item => (global::RoadGuardSystem.DTOs.Reporting.CaseReadFactV1)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReadFactV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.CaseReadFactV1)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReportRefV1Fact item => (global::RoadGuardSystem.DTOs.Reporting.CaseReportRefV1)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.CaseReportRefV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.CaseReportRefV1)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageCalibrationInputFact item => (global::RoadGuardSystem.DTOs.Projects.ChainageCalibrationInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageCalibrationInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.ChainageCalibrationInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageControlFact item => (global::RoadGuardSystem.DTOs.Projects.ChainageControl)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.ChainageControlFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.ChainageControl)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ConfirmRetentionBasisRequestFact item => (global::RoadGuardSystem.DTOs.Retention.ConfirmRetentionBasisRequest)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ConfirmRetentionBasisRequestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.ConfirmRetentionBasisRequest)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.CreateAiMockRunRequestFact item => (global::RoadGuardSystem.DTOs.Processing.CreateAiMockRunRequest)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Processing.CreateAiMockRunRequestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Processing.CreateAiMockRunRequest)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.CreateExportRequestFact item => (global::RoadGuardSystem.DTOs.Exports.CreateExportRequestDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.CreateExportRequestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Exports.CreateExportRequestDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionEvaluationRequestFact item => (global::RoadGuardSystem.DTOs.Retention.CreateRetentionEvaluationRequest)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionEvaluationRequestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.CreateRetentionEvaluationRequest)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionHoldRequestFact item => (global::RoadGuardSystem.DTOs.Retention.CreateRetentionHoldRequest)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.CreateRetentionHoldRequestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.CreateRetentionHoldRequest)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsControlPointFact item => (global::RoadGuardSystem.DTOs.Projects.CrsControlPoint)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsControlPointFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.CrsControlPoint)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsEllipsoidDefinitionFact item => (global::RoadGuardSystem.DTOs.Projects.CrsEllipsoidDefinition)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsEllipsoidDefinitionFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.CrsEllipsoidDefinition)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileInputFact item => (global::RoadGuardSystem.DTOs.Projects.CrsProfileInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.CrsProfileInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileViewFact item => (global::RoadGuardSystem.DTOs.Projects.CrsProfileView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProfileViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.CrsProfileView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProjectionDefinitionFact item => (global::RoadGuardSystem.DTOs.Projects.CrsProjectionDefinition)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsProjectionDefinitionFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.CrsProjectionDefinition)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsTransformOperationFact item => (global::RoadGuardSystem.DTOs.Projects.CrsTransformOperation)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.CrsTransformOperationFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.CrsTransformOperation)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectGeometryFact item => (global::RoadGuardSystem.DTOs.Defects.DefectGeometryDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectGeometryFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Defects.DefectGeometryDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectPageFact item => (global::RoadGuardSystem.DTOs.Defects.DefectPageDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectPageFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Defects.DefectPageDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.DefectReadFactV1Fact item => (global::RoadGuardSystem.DTOs.Reporting.DefectReadFactV1)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.DefectReadFactV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.DefectReadFactV1)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectViewFact item => (global::RoadGuardSystem.DTOs.Defects.DefectViewDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Defects.DefectViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Defects.DefectViewDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportFileFact item => (global::RoadGuardSystem.DTOs.Exports.ExportFileDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportFileFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Exports.ExportFileDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportLabelFact item => (global::RoadGuardSystem.DTOs.Exports.ExportLabelDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportLabelFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Exports.ExportLabelDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportManifestV1Fact item => (global::RoadGuardSystem.DTOs.Exports.ExportManifestV1Dto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportManifestV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Exports.ExportManifestV1Dto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSectionFact item => (global::RoadGuardSystem.DTOs.Exports.ExportSectionDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSectionFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Exports.ExportSectionDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSnapshotPayloadFact item => (global::RoadGuardSystem.DTOs.Exports.ExportSnapshotPayloadDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSnapshotPayloadFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Exports.ExportSnapshotPayloadDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSourceRevisionFact item => (global::RoadGuardSystem.DTOs.Exports.ExportSourceRevisionDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Exports.ExportSourceRevisionFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Exports.ExportSourceRevisionDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceDeclarationFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceDeclaration)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceDeclarationFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceDeclaration)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceReuseInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceReuseInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldEvidenceReuseInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldEvidenceReuseInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldHandoverInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldHandoverInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldHandoverInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldHandoverInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldLocationImpactActionInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldLocationImpactActionInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldLocationImpactActionInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldLocationImpactActionInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldMeasurementInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldMeasurementInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldMeasurementInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldMeasurementInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldPositionProofInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldPositionProofInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldPositionProofInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldPositionProofInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldReviewInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldReviewInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewViewFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldReviewView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldReviewViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldReviewView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldStartInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldStartInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldStartInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldStartInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionViewFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldSubmissionViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldSubmissionView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskActionInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldTaskActionInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskActionInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldTaskActionInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskCreateInputFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldTaskCreateInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskCreateInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldTaskCreateInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskViewFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldTaskView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldTaskViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldTaskView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceFactsFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceFacts)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceFactsFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceFacts)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceQueryFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceQuery)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldVerificationSourceQueryFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldVerificationSourceQuery)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldWorkflowResultFact item => (global::RoadGuardSystem.DTOs.Inspections.FieldWorkflowResult)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Inspections.FieldWorkflowResultFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Inspections.FieldWorkflowResult)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryAffectedReferenceFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryAffectedReference)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryAffectedReferenceFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryAffectedReference)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryConfirmInputFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryConfirmInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryConfirmInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryConfirmInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftInputFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryDraftInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryDraftInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftReadinessFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryDraftReadiness)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftReadinessFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryDraftReadiness)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftViewFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryDraftView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryDraftViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryDraftView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactDecisionInputFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryImpactDecisionInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactDecisionInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryImpactDecisionInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactInputFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryImpactInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryImpactInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryImpactInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapFeatureFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapFeature)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapFeatureFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapFeature)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapLayerFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapLayer)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapLayerFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapLayer)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapManifestFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapManifest)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapManifestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapManifest)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPageFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapPage)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPageFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapPage)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPublishInputFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapPublishInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapPublishInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapPublishInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapSnapshotFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapSnapshot)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryMapSnapshotFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryMapSnapshot)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPackageViewFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryPackageView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPackageViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryPackageView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPointFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryPoint)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPointFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryPoint)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPreviewFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryPreview)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryPreviewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryPreview)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryShapeFact item => (global::RoadGuardSystem.DTOs.Projects.GeometryShape)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.GeometryShapeFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.GeometryShape)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.InternalCaseFact item => (global::RoadGuardSystem.DTOs.Cases.InternalCaseDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Cases.InternalCaseFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Cases.InternalCaseDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.LabelAnnotationFact item => (global::RoadGuardSystem.DTOs.Labels.LabelAnnotationDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.LabelAnnotationFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Labels.LabelAnnotationDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentInputFact item => (global::RoadGuardSystem.DTOs.Projects.NativeAlignmentInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.NativeAlignmentInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentPrimitiveFact item => (global::RoadGuardSystem.DTOs.Projects.NativeAlignmentPrimitive)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.NativeAlignmentPrimitiveFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.NativeAlignmentPrimitive)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportFact item => (global::RoadGuardSystem.DTOs.Reports.OwnReportDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reports.OwnReportDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportEvidenceFact item => (global::RoadGuardSystem.DTOs.Reports.OwnReportEvidenceDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportEvidenceFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reports.OwnReportEvidenceDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportPageFact item => (global::RoadGuardSystem.DTOs.Reports.OwnReportPageDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportPageFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reports.OwnReportPageDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportSupplementFact item => (global::RoadGuardSystem.DTOs.Reports.OwnReportSupplementDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportSupplementFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reports.OwnReportSupplementDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportUpdateFact item => (global::RoadGuardSystem.DTOs.Reports.OwnReportUpdateDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.OwnReportUpdateFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reports.OwnReportUpdateDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementGeometryPreviewFact item => (global::RoadGuardSystem.DTOs.Projects.PavementGeometryPreview)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementGeometryPreviewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.PavementGeometryPreview)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutInputFact item => (global::RoadGuardSystem.DTOs.Projects.PavementLayoutInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.PavementLayoutInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutPreviewFact item => (global::RoadGuardSystem.DTOs.Projects.PavementLayoutPreview)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementLayoutPreviewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.PavementLayoutPreview)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementPlanCreateInputFact item => (global::RoadGuardSystem.DTOs.Projects.PavementPlanCreateInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementPlanCreateInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.PavementPlanCreateInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementWidthIntervalFact item => (global::RoadGuardSystem.DTOs.Projects.PavementWidthInterval)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PavementWidthIntervalFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.PavementWidthInterval)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PlannedSlabCellFact item => (global::RoadGuardSystem.DTOs.Projects.PlannedSlabCell)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.PlannedSlabCellFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.PlannedSlabCell)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ProjectSummaryV1Fact item => (global::RoadGuardSystem.DTOs.Reporting.ProjectSummaryV1)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ProjectSummaryV1Fact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ProjectSummaryV1)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ReleaseRetentionHoldRequestFact item => (global::RoadGuardSystem.DTOs.Retention.ReleaseRetentionHoldRequest)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.ReleaseRetentionHoldRequestFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.ReleaseRetentionHoldRequest)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.ReportEvidenceLocationFact item => (global::RoadGuardSystem.DTOs.Reports.ReportEvidenceLocationDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reports.ReportEvidenceLocationFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reports.ReportEvidenceLocationDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingAvailabilityFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingAvailabilityDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingAvailabilityFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingAvailabilityDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingCaptureFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingCaptureDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingCaptureFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingCaptureDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingDimensionsFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingDimensionsDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingDimensionsFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingDimensionsDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFileFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingFileDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFileFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingFileDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFiltersFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingFiltersDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingFiltersFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingFiltersDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingItemFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingItemDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingItemFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingItemDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingMetricFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingMetricDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingMetricFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingMetricDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingSourceRefFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingSourceRefDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingSourceRefFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingSourceRefDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingTimelineItemFact item => (global::RoadGuardSystem.DTOs.Reporting.ReportingTimelineItemDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Reporting.ReportingTimelineItemFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Reporting.ReportingTimelineItemDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionBasisViewFact item => (global::RoadGuardSystem.DTOs.Retention.RetentionBasisView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionBasisViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.RetentionBasisView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionEvaluationViewFact item => (global::RoadGuardSystem.DTOs.Retention.RetentionEvaluationView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionEvaluationViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.RetentionEvaluationView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionFileViewFact item => (global::RoadGuardSystem.DTOs.Retention.RetentionFileView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionFileViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.RetentionFileView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionHoldViewFact item => (global::RoadGuardSystem.DTOs.Retention.RetentionHoldView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionHoldViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.RetentionHoldView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionItemViewFact item => (global::RoadGuardSystem.DTOs.Retention.RetentionItemView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionItemViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.RetentionItemView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionReferenceViewFact item => (global::RoadGuardSystem.DTOs.Retention.RetentionReferenceView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionReferenceViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.RetentionReferenceView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionWarrantyViewFact item => (global::RoadGuardSystem.DTOs.Retention.RetentionWarrantyView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Retention.RetentionWarrantyViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Retention.RetentionWarrantyView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RoadGeometryVersionViewFact item => (global::RoadGuardSystem.DTOs.Projects.RoadGeometryVersionView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RoadGeometryVersionViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.RoadGeometryVersionView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemInputFact item => (global::RoadGuardSystem.DTOs.Projects.RouteSystemInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.RouteSystemInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemViewFact item => (global::RoadGuardSystem.DTOs.Projects.RouteSystemView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.RouteSystemViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.RouteSystemView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentDefinitionFact item => (global::RoadGuardSystem.DTOs.Projects.SegmentDefinition)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentDefinitionFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.SegmentDefinition)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryFact item => (global::RoadGuardSystem.DTOs.Projects.SegmentGeometry)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.SegmentGeometry)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryViewFact item => (global::RoadGuardSystem.DTOs.Projects.SegmentGeometryView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentGeometryViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.SegmentGeometryView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPreviewFact item => (global::RoadGuardSystem.DTOs.Projects.SegmentPreview)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPreviewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.SegmentPreview)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPublishInputFact item => (global::RoadGuardSystem.DTOs.Projects.SegmentPublishInput)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentPublishInputFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.SegmentPublishInput)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentSetViewFact item => (global::RoadGuardSystem.DTOs.Projects.SegmentSetView)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SegmentSetViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.SegmentSetView)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SlabGeometrySnapshotFact item => (global::RoadGuardSystem.DTOs.Projects.SlabGeometrySnapshot)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.SlabGeometrySnapshotFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.SlabGeometrySnapshot)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelPageFact item => (global::RoadGuardSystem.DTOs.Labels.TrainingLabelPageDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelPageFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Labels.TrainingLabelPageDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelViewFact item => (global::RoadGuardSystem.DTOs.Labels.TrainingLabelViewDto)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Labels.TrainingLabelViewFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Labels.TrainingLabelViewDto)item).ToArray(),
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.WidthProfileItemFact item => (global::RoadGuardSystem.DTOs.Projects.WidthProfileItem)item,
        global::RoadGuardSystem.BusinessObjects.PersistenceFacts.Projects.WidthProfileItemFact[] items => items.Select(item => (global::RoadGuardSystem.DTOs.Projects.WidthProfileItem)item).ToArray(),
        _ => value
    };
}
